/**
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import fs from 'fs';
import path from 'path';
import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  PageNumber,
  Header,
  Footer,
  ImageRun
} from 'docx';
import { logger } from '../utils/logger.js';

export interface DocxDocumentOptions {
  imageUrl?: string;
  imageBuffer?: Buffer;
  caption?: string;
}

export interface PptxPresentationOptions {
  pptxDownloadUrl?: string;
  pdfDownloadUrl?: string;
  slidesData?: Array<{
    title?: string;
    description?: string;
    fullDescription?: string;
    image?: { url: string; width?: number; height?: number };
  }>;
}

export interface DocumentHtmlOptions {
  imageUrl?: string;
}

export class NotebookLmArtifactFormatter {
  /**
   * Formats internal Discovery Engine artifact types into clean, human-readable labels.
   */
  public static formatArtifactTypeName(type?: string): string {
    switch (type) {
      case 'ARTIFACT_TYPE_SLIDES': return 'Slide Deck';
      case 'ARTIFACT_TYPE_INFOGRAPHIC': return 'Infographic';
      case 'ARTIFACT_TYPE_TAILORED_REPORT': return 'Briefing Document / Report';
      case 'ARTIFACT_TYPE_AUDIO_OVERVIEW': return 'Audio Overview';
      case 'ARTIFACT_TYPE_MIND_MAP': return 'Mind Map';
      case 'ARTIFACT_TYPE_EXPLAINER_VIDEO': return 'Video Overview';
      case 'ARTIFACT_TYPE_APP': return 'Interactive App (Quiz / Flashcards)';
      default: return 'Studio Document';
    }
  }

  /**
   * Extracts structured text and analysis from Studio artifacts (Slide Decks, Infographics, Reports, etc.)
   */
  public static extractTextFromArtifact(artifact: any): string {
    if (!artifact) return '';

    // 1. Slide Deck Artifacts
    if (artifact.slides?.slides && Array.isArray(artifact.slides.slides)) {
      let content = `# Slide Deck: ${artifact.title || artifact.slides.title || 'Presentation'}\n\n`;
      artifact.slides.slides.forEach((slide: any, idx: number) => {
        content += `## Slide ${idx + 1}: ${slide.title || 'Slide'}\n`;
        if (slide.fullDescription) {
          content += `${slide.fullDescription}\n\n`;
        } else if (slide.description) {
          content += `${slide.description}\n\n`;
        }
      });
      return content.trim();
    }

    // 2. Infographics
    if (artifact.infographic?.infographics && Array.isArray(artifact.infographic.infographics)) {
      let content = `# Infographic: ${artifact.title || artifact.infographic.title || 'Infographic'}\n\n`;
      artifact.infographic.infographics.forEach((info: any, idx: number) => {
        content += `## Section ${idx + 1}: ${info.title || 'Section'}\n`;
        if (info.fullDescription) {
          content += `${info.fullDescription}\n\n`;
        } else if (info.description) {
          content += `${info.description}\n\n`;
        }
      });
      return content.trim();
    }

    // 3. Tailored Reports / Briefing Docs
    if (artifact.tailoredReport?.content) {
      return artifact.tailoredReport.content;
    }

    // 4. Interactive Learning Apps (Quizzes / Flashcards)
    if (artifact.app || artifact.rawArtifact?.app) {
      const appData = this.extractAppData(artifact);
      if (appData?.quiz && Array.isArray(appData.quiz)) {
        return this.formatQuizMarkdown(artifact.title || 'Quiz', 'Notebook', appData.quiz);
      }
      if (appData?.flashcards && Array.isArray(appData.flashcards)) {
        return this.formatFlashcardsMarkdown(artifact.title || 'Flashcards', 'Notebook', appData.flashcards);
      }
      return `# Interactive App: ${artifact.title || 'Studio App'}\n\nThis is an authentic, self-contained interactive HTML5 learning application (Quiz / Flashcards) generated by NotebookLM Studio. The application is preserved as an offline HTML file.`;
    }

    // 5. Explainer Video Overview
    if (artifact.explainerVideo) {
      return `# Video Overview: ${artifact.title || 'Video Overview'}\n\nHigh-definition video overview synthesized by NotebookLM Studio. Preserved as an MP4 media file.`;
    }

    // 6. Audio Overview / Podcast
    if (artifact.audioOverview) {
      return `# Audio Overview: ${artifact.title || 'Audio Overview'}\n\nAutonomous multi-speaker podcast audio overview synthesized by NotebookLM Studio. Preserved as a high-fidelity WAV audio file.`;
    }

    return artifact.content || '';
  }

  /**
   * Generates a clean, professional, human-readable filename matching NotebookLM direct exports.
   * Eliminates duplicate names, double underscores, and boilerplate tags like "(Restored)".
   */
  public static cleanArtifactFilename(notebookName: string, artifactTitle: string, extension: string): string {
    const cleanNb = (notebookName || 'Notebook')
      .replace(/\s*\((?:Restored|Copy|\d+)\)\s*/gi, '')
      .replace(/[:\/\\*?"<>|]+/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    let cleanArt = (artifactTitle || 'Artifact')
      .replace(/\s*\((?:Restored|Copy|\d+)\)\s*/gi, '')
      .replace(/[:\/\\*?"<>|]+/g, ' ')
      .replace(/\s+/g, ' ')
      .trim();

    // If the artifact title already begins with or contains the notebook title, avoid duplicate prefix
    if (cleanNb && cleanArt.toLowerCase().startsWith(cleanNb.toLowerCase())) {
      cleanArt = cleanArt.substring(cleanNb.length).replace(/^[\s-_:]+/, '').trim();
    }

    let finalBase = '';
    if (!cleanArt || cleanArt.toLowerCase() === cleanNb.toLowerCase()) {
      finalBase = cleanNb || 'NotebookLM_Export';
    } else if (!cleanNb) {
      finalBase = cleanArt;
    } else {
      finalBase = `${cleanNb} - ${cleanArt}`;
    }

    // Limit filename length safely
    if (finalBase.length > 120) {
      finalBase = finalBase.substring(0, 120).trim();
    }

    finalBase = finalBase.replace(/\.+$/, '').trim();
    const ext = !extension ? '' : extension.startsWith('.') ? extension : `.${extension}`;
    return `${finalBase}${ext}`;
  }

  /**
   * Cleans artifact Markdown to ensure authentic direct-from-NotebookLM formatting without artificial debug noise.
   */
  public static cleanNotebookLmMarkdown(title: string, rawContent: string): string {
    if (!rawContent) return `# ${title}\n\n`;

    let cleaned = rawContent
      // Remove artificial header markers
      .replace(/^\s*\*\*Artifact Type:\*\*\s*`?[^`\n]+`?\s*(\n\s*---\s*)?/im, '')
      .trim();

    // If the content does not start with a heading, prepend a Level 1 Heading
    if (!cleaned.startsWith('# ')) {
      cleaned = `# ${title}\n\n${cleaned}`;
    }

    return cleaned + '\n';
  }

  /**
   * Parses inline markdown tokens into an array of docx TextRun objects.
   * Handles bold, italic, bold-italic, inline code, and citations like [1], [Roshar: Surgebinding].
   */
  public static parseInlineMarkdown(text: string): TextRun[] {
    const runs: TextRun[] = [];
    if (!text) return runs;

    // Tokenize inline markdown: ***bold-italic***, **bold**, *italic*, `code`, and [citation]
    const tokenRegex = /(\*\*\*[^*]+\*\*\*|\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`|\[[0-9]+\]|\[[^\]]+\])/g;
    let lastIndex = 0;
    let match: RegExpExecArray | null;

    while ((match = tokenRegex.exec(text)) !== null) {
      if (match.index > lastIndex) {
        const plain = text.substring(lastIndex, match.index);
        runs.push(new TextRun({ text: plain, font: 'Arial', size: 21, color: '1E293B' }));
      }

      const token = match[0];
      if (token.startsWith('***') && token.endsWith('***')) {
        runs.push(new TextRun({
          text: token.slice(3, -3),
          bold: true,
          italics: true,
          font: 'Arial',
          size: 21,
          color: '0F172A'
        }));
      } else if (token.startsWith('**') && token.endsWith('**')) {
        runs.push(new TextRun({
          text: token.slice(2, -2),
          bold: true,
          font: 'Arial',
          size: 21,
          color: '0F172A'
        }));
      } else if (token.startsWith('*') && token.endsWith('*')) {
        runs.push(new TextRun({
          text: token.slice(1, -1),
          italics: true,
          font: 'Arial',
          size: 21,
          color: '334155'
        }));
      } else if (token.startsWith('`') && token.endsWith('`')) {
        runs.push(new TextRun({
          text: token.slice(1, -1),
          font: 'Consolas',
          size: 19,
          shading: { fill: 'F1F5F9' },
          color: '0F172A'
        }));
      } else if (token.startsWith('[') && token.endsWith(']')) {
        // Citation badge or visual cue
        runs.push(new TextRun({
          text: token,
          font: 'Arial',
          size: 18,
          bold: true,
          color: '2563EB'
        }));
      }

      lastIndex = tokenRegex.lastIndex;
    }

    if (lastIndex < text.length) {
      runs.push(new TextRun({
        text: text.substring(lastIndex),
        font: 'Arial',
        size: 21,
        color: '1E293B'
      }));
    }

    return runs.length > 0 ? runs : [new TextRun({ text, font: 'Arial', size: 21, color: '1E293B' })];
  }

  /**
   * Generates a high-fidelity Microsoft Word (.docx) document matching direct NotebookLM / Google Docs exports.
   * Implements full Markdown support: Headings, Paragraphs, Inline Bold/Italic, Native Tables, Bullet/Numbered Lists, Blockquotes.
   */
  public static async generateDocxDocument(
    title: string,
    type: string,
    notebookName: string,
    content: string,
    outputPath: string,
    options?: DocxDocumentOptions
  ): Promise<void> {
    try {
      const children: Array<Paragraph | Table> = [];

      // Document Title Heading
      children.push(
        new Paragraph({
          text: title,
          heading: HeadingLevel.TITLE,
          spacing: { after: 120 }
        })
      );

      // Subtitle with Notebook context
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: 'Notebook: ', bold: true, color: '475569', font: 'Arial', size: 20 }),
            new TextRun({ text: `${notebookName}   •   `, color: '64748B', font: 'Arial', size: 20 }),
            new TextRun({ text: 'Artifact: ', bold: true, color: '475569', font: 'Arial', size: 20 }),
            new TextRun({ text: `${type} (NotebookLM Studio)`, color: '2563EB', font: 'Arial', size: 20 })
          ],
          spacing: { after: 240 }
        })
      );

      // Embed high-resolution graphic/infographic image if provided
      let imgBuffer = options?.imageBuffer;
      if (!imgBuffer && options?.imageUrl) {
        try {
          const res = await fetch(options.imageUrl);
          if (res.ok) {
            imgBuffer = Buffer.from(await res.arrayBuffer());
          }
        } catch (imgErr: any) {
          logger.debug(`Could not download image for DOCX embedding: ${imgErr.message}`);
        }
      }

      if (imgBuffer && imgBuffer.length > 0) {
        const isPng = imgBuffer.length >= 8 && imgBuffer[0] === 0x89 && imgBuffer[1] === 0x50;
        const imgType: 'png' | 'jpg' = isPng ? 'png' : 'jpg';

        children.push(
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new ImageRun({
                data: imgBuffer,
                type: imgType,
                transformation: {
                  width: 580,
                  height: 380
                }
              })
            ],
            spacing: { after: 120 }
          })
        );

        if (options?.caption) {
          children.push(
            new Paragraph({
              alignment: AlignmentType.CENTER,
              children: [
                new TextRun({
                  text: options.caption,
                  italics: true,
                  size: 18,
                  color: '64748B',
                  font: 'Arial'
                })
              ],
              spacing: { after: 360 }
            })
          );
        } else {
          children.push(
            new Paragraph({
              spacing: { after: 240 }
            })
          );
        }
      }

      const lines = content.split('\n');
      let i = 0;

      while (i < lines.length) {
        const rawLine = lines[i];
        const line = rawLine.trim();

        if (!line) {
          i++;
          continue;
        }

        // 1. Markdown Table parsing
        if (line.startsWith('|') && line.endsWith('|')) {
          const tableLines: string[] = [];
          while (i < lines.length && lines[i].trim().startsWith('|') && lines[i].trim().endsWith('|')) {
            tableLines.push(lines[i].trim());
            i++;
          }

          if (tableLines.length >= 2) {
            const tableRows: TableRow[] = [];
            const headerRowLine = tableLines[0];
            const headerCols = headerRowLine
              .split('|')
              .slice(1, -1)
              .map(c => c.trim());

            // Build header row
            tableRows.push(
              new TableRow({
                tableHeader: true,
                children: headerCols.map(colText => new TableCell({
                  shading: { fill: 'F1F5F9' },
                  margins: { top: 120, bottom: 120, left: 160, right: 160 },
                  children: [
                    new Paragraph({
                      children: [new TextRun({ text: colText, bold: true, font: 'Arial', size: 20, color: '0F172A' })],
                      spacing: { after: 40 }
                    })
                  ]
                }))
              })
            );

            // Process data rows (skip index 1 if it's separator |---|---|)
            const dataStartIndex = tableLines[1].includes('---') ? 2 : 1;
            for (let rIdx = dataStartIndex; rIdx < tableLines.length; rIdx++) {
              const rowCols = tableLines[rIdx]
                .split('|')
                .slice(1, -1)
                .map(c => c.trim());

              const isEven = (rIdx - dataStartIndex) % 2 === 1;
              tableRows.push(
                new TableRow({
                  children: rowCols.map(colText => new TableCell({
                    shading: { fill: isEven ? 'F8FAFC' : 'FFFFFF' },
                    margins: { top: 100, bottom: 100, left: 160, right: 160 },
                    children: [
                      new Paragraph({
                        children: NotebookLmArtifactFormatter.parseInlineMarkdown(colText),
                        spacing: { after: 40 }
                      })
                    ]
                  }))
                })
              );
            }

            children.push(
              new Table({
                width: { size: 100, type: WidthType.PERCENTAGE },
                borders: {
                  top: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
                  bottom: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
                  left: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
                  right: { style: BorderStyle.SINGLE, size: 1, color: 'CBD5E1' },
                  insideHorizontal: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' },
                  insideVertical: { style: BorderStyle.SINGLE, size: 1, color: 'E2E8F0' }
                },
                rows: tableRows
              })
            );

            children.push(new Paragraph({ spacing: { after: 160 } }));
            continue;
          }
        }

        // 2. Headings
        if (line.startsWith('# ')) {
          const headingText = line.replace(/^#\s+/, '').trim();
          if (headingText.toLowerCase() !== title.toLowerCase()) {
            children.push(
              new Paragraph({
                text: headingText,
                heading: HeadingLevel.HEADING_1,
                spacing: { before: 280, after: 120 }
              })
            );
          }
          i++;
          continue;
        }

        if (line.startsWith('## ')) {
          children.push(
            new Paragraph({
              text: line.replace(/^##\s+/, '').trim(),
              heading: HeadingLevel.HEADING_2,
              spacing: { before: 220, after: 100 }
            })
          );
          i++;
          continue;
        }

        if (line.startsWith('### ')) {
          children.push(
            new Paragraph({
              text: line.replace(/^###\s+/, '').trim(),
              heading: HeadingLevel.HEADING_3,
              spacing: { before: 180, after: 80 }
            })
          );
          i++;
          continue;
        }

        if (line.startsWith('#### ')) {
          children.push(
            new Paragraph({
              text: line.replace(/^####\s+/, '').trim(),
              heading: HeadingLevel.HEADING_4,
              spacing: { before: 140, after: 60 }
            })
          );
          i++;
          continue;
        }

        // 3. Blockquotes
        if (line.startsWith('> ')) {
          const quoteText = line.replace(/^>\s+/, '').trim();
          children.push(
            new Paragraph({
              indent: { left: 720 },
              border: { left: { color: '3B82F6', size: 24, style: BorderStyle.SINGLE, space: 140 } },
              children: NotebookLmArtifactFormatter.parseInlineMarkdown(quoteText),
              spacing: { before: 120, after: 120 }
            })
          );
          i++;
          continue;
        }

        // 4. Horizontal Rule
        if (line === '---' || line === '***' || line === '___') {
          children.push(
            new Paragraph({
              border: { bottom: { color: 'E2E8F0', size: 6, style: BorderStyle.SINGLE, space: 100 } },
              spacing: { before: 140, after: 140 }
            })
          );
          i++;
          continue;
        }

        // 5. Bullet List Items
        const bulletMatch = rawLine.match(/^(\s*)([-*])\s+(.*)$/);
        if (bulletMatch) {
          const indentSpaces = bulletMatch[1].length;
          const bulletText = bulletMatch[3];
          const level = indentSpaces >= 4 ? 2 : indentSpaces >= 2 ? 1 : 0;

          children.push(
            new Paragraph({
              bullet: { level },
              children: NotebookLmArtifactFormatter.parseInlineMarkdown(bulletText),
              spacing: { after: 60 }
            })
          );
          i++;
          continue;
        }

        // 6. Numbered List Items
        const numberedMatch = rawLine.match(/^(\s*)(\d+)\.\s+(.*)$/);
        if (numberedMatch) {
          const num = numberedMatch[2];
          const itemText = numberedMatch[3];
          const runs = [
            new TextRun({ text: `${num}. `, bold: true, color: '0F172A', font: 'Arial', size: 21 }),
            ...NotebookLmArtifactFormatter.parseInlineMarkdown(itemText)
          ];

          children.push(
            new Paragraph({
              children: runs,
              indent: { left: 360 },
              spacing: { after: 60 }
            })
          );
          i++;
          continue;
        }

        // 7. Regular Paragraph
        children.push(
          new Paragraph({
            children: NotebookLmArtifactFormatter.parseInlineMarkdown(line),
            spacing: { after: 120, line: 276 }
          })
        );
        i++;
      }

      const doc = new Document({
        styles: {
          default: {
            document: {
              run: { font: 'Arial', size: 21, color: '1E293B' }
            }
          }
        },
        sections: [{
          properties: {
            page: {
              margin: {
                top: 1440,
                bottom: 1440,
                left: 1440,
                right: 1440
              }
            }
          },
          headers: {
            default: new Header({
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [
                    new TextRun({ text: title, color: '94A3B8', font: 'Arial', size: 16 })
                  ]
                })
              ]
            })
          },
          footers: {
            default: new Footer({
              children: [
                new Paragraph({
                  alignment: AlignmentType.RIGHT,
                  children: [
                    new TextRun({ text: 'NotebookLM • Page ', color: '94A3B8', font: 'Arial', size: 16 }),
                    new TextRun({ children: [PageNumber.CURRENT], color: '94A3B8', font: 'Arial', size: 16 }),
                    new TextRun({ text: ' of ', color: '94A3B8', font: 'Arial', size: 16 }),
                    new TextRun({ children: [PageNumber.TOTAL_PAGES], color: '94A3B8', font: 'Arial', size: 16 })
                  ]
                })
              ]
            })
          },
          children
        }]
      });

      const buffer = await Packer.toBuffer(doc);
      fs.writeFileSync(outputPath, buffer);
      logger.info(`Generated high-fidelity DOCX export: ${outputPath} (${buffer.length} bytes)`);
    } catch (err: any) {
      logger.warn(`Could not generate DOCX for "${title}": ${err.message}`);
    }
  }

  /**
   * Generates a high-fidelity Microsoft PowerPoint (.pptx) presentation matching direct NotebookLM / Google Slides exports.
   * Widescreen 16:9, clean executive design, structured card layouts, bullet point bold lead-ins, and speaker notes.
   */
  public static async generatePptxPresentation(
    title: string,
    notebookName: string,
    content: string,
    outputPath: string,
    options?: PptxPresentationOptions
  ): Promise<void> {
    try {
      // 1. If official Google Cloud Storage PPTX pre-signed URL is available, download direct native PPTX
      if (options?.pptxDownloadUrl) {
        try {
          logger.info(`Downloading official native NotebookLM PPTX from Google Cloud Storage for "${title}"...`);
          const res = await fetch(options.pptxDownloadUrl);
          if (res.ok) {
            const buffer = Buffer.from(await res.arrayBuffer());
            if (buffer.length > 1024) {
              fs.writeFileSync(outputPath, buffer);
              logger.info(`Successfully preserved official native NotebookLM PPTX: ${outputPath} (${buffer.length} bytes)`);

              // Download companion native PDF if provided
              if (options.pdfDownloadUrl) {
                const pdfPath = outputPath.replace(/\.pptx$/i, '.pdf');
                try {
                  const pdfRes = await fetch(options.pdfDownloadUrl);
                  if (pdfRes.ok) {
                    const pdfBuf = Buffer.from(await pdfRes.arrayBuffer());
                    fs.writeFileSync(pdfPath, pdfBuf);
                    logger.info(`Successfully preserved official native NotebookLM PDF: ${pdfPath} (${pdfBuf.length} bytes)`);
                  }
                } catch (pdfErr: any) {
                  logger.debug(`Could not download companion PDF: ${pdfErr.message}`);
                }
              }

              return;
            }
          }
        } catch (downloadErr: any) {
          logger.warn(`Failed to download official PPTX from signed URL: ${downloadErr.message}. Falling back to presentation synthesis.`);
        }
      }

      // 2. If the file already exists on disk and is substantive (> 500 KB), DO NOT overwrite with fallback!
      if (fs.existsSync(outputPath) && fs.statSync(outputPath).size > 500 * 1024) {
        logger.info(`Preserving existing substantive PowerPoint export: ${outputPath} (${fs.statSync(outputPath).size} bytes)`);
        return;
      }

      const pptxModule: any = await import('pptxgenjs');
      const PptxConstructor = pptxModule.default || pptxModule;
      const pres = new PptxConstructor();

      pres.title = title;
      pres.subject = `Exported from Gemini Enterprise Notebook: ${notebookName}`;
      pres.layout = 'LAYOUT_16x9';

      // 1. Title Slide (Clean modern executive style)
      const titleSlide = pres.addSlide();
      titleSlide.background = { color: 'FFFFFF' };

      // Category Pill
      titleSlide.addShape(pres.ShapeType.roundRect, {
        x: 1.0,
        y: 1.4,
        w: 2.6,
        h: 0.35,
        fill: { color: 'EFF6FF' },
        line: { color: 'BFDBFE', width: 1 }
      });
      titleSlide.addText('NOTEBOOKLM PRESENTATION', {
        x: 1.0,
        y: 1.4,
        w: 2.6,
        h: 0.35,
        fontSize: 10,
        bold: true,
        color: '1D4ED8',
        align: 'center',
        valign: 'middle'
      });

      // Big Title
      titleSlide.addText(title, {
        x: 1.0,
        y: 2.0,
        w: '80%',
        h: 2.0,
        fontSize: 32,
        bold: true,
        color: '0F172A',
        fontFace: 'Arial',
        align: 'left',
        valign: 'top'
      });

      // Accent Line
      titleSlide.addShape(pres.ShapeType.rect, {
        x: 1.0,
        y: 4.2,
        w: 1.5,
        h: 0.05,
        fill: { color: '1A73E8' },
        line: { color: '1A73E8' }
      });

      // Subtitle
      titleSlide.addText(`Notebook: ${notebookName}\nGenerated via Gemini Enterprise NotebookLM Studio`, {
        x: 1.0,
        y: 4.5,
        w: '80%',
        h: 0.8,
        fontSize: 13,
        color: '64748B',
        fontFace: 'Arial',
        align: 'left'
      });

      // 2. Parse Slide Deck Segments
      let rawSlides = content
        .split(/(?:\n\s*---\s*\n|\n\s*\*\*\*\s*\n|^##\s+Slide\s+\d+:?|^###\s+Slide\s+\d+:?)/im)
        .map(s => s.trim())
        .filter(s => s.length > 0);

      if (rawSlides.length <= 1) {
        const h2Slides = content.split(/^##\s+/m).map(s => s.trim()).filter(s => s.length > 0);
        if (h2Slides.length > 1) {
          rawSlides = h2Slides;
        }
      }

      const slides = rawSlides.length > 0 ? rawSlides : [content];

      for (let i = 0; i < slides.length; i++) {
        const s = slides[i];
        const lines = s.split('\n').map(l => l.trim()).filter(Boolean);
        if (lines.length === 0) continue;

        let slideTitle = lines[0].replace(/^[#*-]+\s*/, '').replace(/^Slide\s+\d+:?\s*/i, '').trim();
        if (!slideTitle || slideTitle.length > 80) {
          slideTitle = `Key Takeaways & Insights (Part ${i + 1})`;
        }

        const bodyLines = lines.slice(1);
        const slide = pres.addSlide();
        slide.background = { color: 'FFFFFF' };

        // Header Accent Pill
        slide.addText(`NOTEBOOKLM • SLIDE ${i + 1} OF ${slides.length}`, {
          x: 0.8,
          y: 0.4,
          w: 4.0,
          h: 0.25,
          fontSize: 9,
          bold: true,
          color: '2563EB',
          fontFace: 'Arial'
        });

        // Slide Title
        slide.addText(slideTitle, {
          x: 0.8,
          y: 0.65,
          w: '85%',
          h: 0.7,
          fontSize: 22,
          bold: true,
          color: '0F172A',
          fontFace: 'Arial',
          align: 'left'
        });

        // Subtle Title Underline Accent
        slide.addShape(pres.ShapeType.rect, {
          x: 0.8,
          y: 1.35,
          w: 1.2,
          h: 0.03,
          fill: { color: '1A73E8' },
          line: { color: '1A73E8' }
        });

        // Separate Speaker Notes
        const contentLines: string[] = [];
        const speakerNotes: string[] = [];
        let inNotes = false;

        for (const line of bodyLines) {
          if (/^(?:Speaker\s+)?Notes?:/i.test(line)) {
            inNotes = true;
            speakerNotes.push(line.replace(/^(?:Speaker\s+)?Notes?:\s*/i, ''));
            continue;
          }
          if (inNotes) {
            speakerNotes.push(line);
          } else {
            contentLines.push(line);
          }
        }

        if (speakerNotes.length > 0) {
          slide.addNotes(speakerNotes.join('\n'));
        }

        // Detect Card / Subsection Layout
        const subSections: Array<{ title: string; bullets: string[] }> = [];
        let curSection: { title: string; bullets: string[] } | null = null;

        for (const line of contentLines) {
          if (line.startsWith('### ') || line.startsWith('**') && line.endsWith('**') && line.length < 50) {
            if (curSection) subSections.push(curSection);
            curSection = {
              title: line.replace(/^###\s+/, '').replace(/\*\*/g, '').trim(),
              bullets: []
            };
          } else if (curSection) {
            curSection.bullets.push(line);
          }
        }
        if (curSection) subSections.push(curSection);

        if (subSections.length >= 2 && subSections.length <= 3) {
          const cardCount = subSections.length;
          const cardWidth = cardCount === 2 ? 4.1 : 2.7;
          const cardGap = cardCount === 2 ? 0.6 : 0.4;
          const startX = 0.8;

          for (let cIdx = 0; cIdx < cardCount; cIdx++) {
            const card = subSections[cIdx];
            const xPos = startX + cIdx * (cardWidth + cardGap);

            slide.addShape(pres.ShapeType.roundRect, {
              x: xPos,
              y: 1.6,
              w: cardWidth,
              h: 4.8,
              fill: { color: 'F8FAFC' },
              line: { color: 'E2E8F0', width: 1 }
            });

            slide.addText(card.title, {
              x: xPos + 0.2,
              y: 1.8,
              w: cardWidth - 0.4,
              h: 0.5,
              fontSize: 14,
              bold: true,
              color: '1E3A8A',
              fontFace: 'Arial'
            });

            const cardRuns: any[] = [];
            for (const b of card.bullets) {
              const cleanB = b.replace(/^[-*]\s+/, '');
              cardRuns.push({
                text: cleanB,
                options: { bullet: true, fontSize: 12, color: '334155', breakLine: true }
              });
            }

            if (cardRuns.length > 0) {
              slide.addText(cardRuns, {
                x: xPos + 0.2,
                y: 2.4,
                w: cardWidth - 0.4,
                h: 3.8,
                valign: 'top',
                margin: 0
              });
            }
          }
        } else {
          // Standard Bullet & Content Layout
          const textItems: any[] = [];
          for (const line of contentLines) {
            if (line.startsWith('- ') || line.startsWith('* ')) {
              const rawBullet = line.replace(/^[-*]\s+/, '');

              const leadInMatch = rawBullet.match(/^\*\*([^*]+)\*\*:\s*(.*)$/);
              if (leadInMatch) {
                textItems.push({
                  text: `${leadInMatch[1]}: `,
                  options: { bullet: true, bold: true, fontSize: 15, color: '1D4ED8', breakLine: false }
                });
                textItems.push({
                  text: leadInMatch[2],
                  options: { fontSize: 15, color: '334155', breakLine: true }
                });
              } else {
                textItems.push({
                  text: rawBullet.replace(/\*\*/g, ''),
                  options: { bullet: true, fontSize: 15, color: '334155', breakLine: true }
                });
              }
            } else if (line.startsWith('[') && line.endsWith(']')) {
              textItems.push({
                text: line.slice(1, -1),
                options: { italic: true, fontSize: 12, color: '2563EB', breakLine: true }
              });
            } else {
              textItems.push({
                text: line.replace(/\*\*/g, ''),
                options: { fontSize: 15, color: '1E293B', breakLine: true }
              });
            }
          }

          if (textItems.length > 0) {
            slide.addText(textItems, {
              x: 0.8,
              y: 1.6,
              w: '85%',
              h: 4.8,
              valign: 'top',
              margin: 0
            });
          }
        }

        slide.addText(`NotebookLM • ${notebookName}`, {
          x: 0.8,
          y: 6.8,
          w: '60%',
          h: 0.3,
          fontSize: 9,
          color: '94A3B8',
          fontFace: 'Arial',
          align: 'left'
        });

        slide.addText(`${i + 1} / ${slides.length}`, {
          x: 8.5,
          y: 6.8,
          w: 1.5,
          h: 0.3,
          fontSize: 9,
          color: '94A3B8',
          fontFace: 'Arial',
          align: 'right'
        });
      }

      const buf = await pres.write({ outputType: 'nodebuffer' });
      fs.writeFileSync(outputPath, buf as Buffer);
      logger.info(`Generated high-fidelity PPTX export: ${outputPath} (${(buf as Buffer).length} bytes)`);
    } catch (err: any) {
      logger.warn(`Could not generate PPTX for "${title}": ${err.message}`);
    }
  }

  /**
   * Renders clean, responsive HTML matching a real Google Docs / NotebookLM preview document.
   */
  public static renderDocumentHtml(
    title: string,
    type: string,
    notebookName: string,
    content: string,
    options?: { imageUrl?: string }
  ): string {
    const formattedBody = content
      .replace(/^# (.*$)/gm, '<h1 style="color: #0f172a; font-size: 26px; font-weight: 800; margin: 28px 0 14px 0; border-bottom: 2px solid #e2e8f0; padding-bottom: 8px;">$1</h1>')
      .replace(/^## (.*$)/gm, '<h2 style="color: #1e3a8a; font-size: 20px; font-weight: 700; margin: 24px 0 12px 0;">$1</h2>')
      .replace(/^### (.*$)/gm, '<h3 style="color: #334155; font-size: 16px; font-weight: 600; margin: 18px 0 8px 0;">$1</h3>')
      .replace(/\*\*\*(.*?)\*\*\*/g, '<strong><em>$1</em></strong>')
      .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #0f172a;">$1</strong>')
      .replace(/\*(.*?)\*/g, '<em>$1</em>')
      .replace(/^- (.*)$/gm, '<li style="margin-bottom: 6px; color: #334155;">$1</li>')
      .replace(/\[(.*?)\]/g, '<span style="background-color: #eff6ff; border: 1px solid #bfdbfe; color: #1d4ed8; padding: 2px 6px; border-radius: 4px; font-size: 11px; font-weight: 600;">$1</span>')
      .replace(/\n\n/g, '<p style="margin: 0 0 12px 0; color: #334155; line-height: 1.7;"></p>');

    const imageBanner = options?.imageUrl
      ? `<div style="text-align: center; margin-bottom: 28px;"><img src="${options.imageUrl}" style="max-width: 100%; max-height: 520px; object-fit: contain; border-radius: 12px; box-shadow: 0 8px 24px rgba(0,0,0,0.12); border: 1px solid #e2e8f0;" alt="${title}"/></div>`
      : '';

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - ${type}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background-color: #f1f5f9;
      color: #1e293b;
      margin: 0;
      padding: 40px 20px;
      line-height: 1.6;
    }
    .doc-container {
      max-width: 840px;
      margin: 0 auto;
      background-color: #ffffff;
      border: 1px solid #e2e8f0;
      border-radius: 12px;
      padding: 48px;
      box-shadow: 0 10px 25px -5px rgba(0, 0, 0, 0.06);
    }
    .doc-header {
      border-bottom: 1px solid #e2e8f0;
      padding-bottom: 20px;
      margin-bottom: 32px;
    }
    .doc-badge {
      background-color: #eff6ff;
      border: 1px solid #bfdbfe;
      color: #1d4ed8;
      font-size: 11px;
      font-weight: 700;
      padding: 4px 10px;
      border-radius: 6px;
      display: inline-block;
      margin-bottom: 12px;
      letter-spacing: 0.5px;
    }
    .doc-title {
      font-size: 28px;
      color: #0f172a;
      margin: 0 0 8px 0;
      font-weight: 800;
    }
    .doc-meta {
      font-size: 13px;
      color: #64748b;
    }
    ul { padding-left: 24px; margin-bottom: 16px; }
    table { width: 100%; border-collapse: collapse; margin: 16px 0; font-size: 14px; }
    th, td { border: 1px solid #cbd5e1; padding: 10px 14px; text-align: left; }
    th { background-color: #f8fafc; font-weight: 700; color: #0f172a; }
    tr:nth-child(even) { background-color: #f8fafc; }
    @media print {
      body { background-color: #ffffff; padding: 0; }
      .doc-container { box-shadow: none; border: none; padding: 0; max-width: 100%; }
    }
  </style>
</head>
<body>
  <div class="doc-container">
    <div class="doc-header">
      <span class="doc-badge">${type.toUpperCase()} • NOTEBOOKLM</span>
      <h1 class="doc-title">${title}</h1>
      <div class="doc-meta">📓 Notebook: <strong>${notebookName}</strong> &bull; Exported from Gemini Enterprise</div>
    </div>
    <div class="doc-body">
      ${imageBanner}
      ${formattedBody}
    </div>
  </div>
</body>
</html>`;
  }

  /**
   * Robust download helper for pre-signed Google Cloud Storage assets.
   */
  public static async downloadFile(url: string, outputPath: string): Promise<boolean> {
    try {
      const res = await fetch(url);
      if (!res.ok) return false;
      const buf = Buffer.from(await res.arrayBuffer());
      if (buf.length < 500) return false;
      fs.writeFileSync(outputPath, buf);
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Renders an interactive 16:9 carousel presentation viewer matching the PowerPoint slide deck.
   */
  public static renderSlideDeckPresentation(title: string, notebookName: string, content: string): string {
    const rawSlides = content
      .split(/(?:\n\s*---\s*\n|\n\s*\*\*\*\s*\n|^##\s+Slide\s+\d+:?|^###\s+Slide\s+\d+:?)/im)
      .map(s => s.trim())
      .filter(s => s.length > 0);

    const slides = rawSlides.length > 0 ? rawSlides : [content];

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${title} - Presentation Deck</title>
  <style>
    body {
      background-color: #0f172a;
      color: #f8fafc;
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      margin: 0;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      padding: 24px;
    }
    .deck-container {
      width: 100%;
      max-width: 960px;
      aspect-ratio: 16 / 9;
      background-color: #ffffff;
      color: #0f172a;
      border-radius: 16px;
      box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
      overflow: hidden;
      display: flex;
      flex-direction: column;
    }
    .slide-header {
      padding: 20px 32px 12px 32px;
      border-bottom: 2px solid #f1f5f9;
      display: flex;
      justify-content: space-between;
      align-items: center;
    }
    .slide-pill {
      background: #eff6ff;
      color: #1d4ed8;
      font-size: 11px;
      font-weight: 700;
      padding: 4px 10px;
      border-radius: 6px;
    }
    .slide-body {
      flex: 1;
      padding: 32px;
      overflow-y: auto;
      font-size: 16px;
      line-height: 1.6;
    }
    .slide-footer {
      padding: 14px 32px;
      background-color: #f8fafc;
      border-top: 1px solid #e2e8f0;
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 12px;
      color: #64748b;
    }
    .slide-content { display: none; }
    .slide-content.active { display: block; }
    .nav-btn {
      background-color: #1e293b;
      color: #ffffff;
      border: none;
      padding: 8px 16px;
      border-radius: 8px;
      font-size: 12px;
      font-weight: 600;
      cursor: pointer;
      transition: background-color 0.2s;
    }
    .nav-btn:hover { background-color: #334155; }
    .nav-btn:disabled { opacity: 0.3; cursor: not-allowed; }
  </style>
</head>
<body>
  <div class="deck-container">
    <div class="slide-header">
      <span class="slide-pill">NOTEBOOKLM PRESENTATION</span>
      <span style="font-size: 12px; color: #64748b; font-family: monospace;" id="slideNum">Slide 1 of ${slides.length}</span>
    </div>
    <div class="slide-body">
      ${slides.map((s, idx) => `
        <div id="slide-${idx}" class="slide-content ${idx === 0 ? 'active' : ''}">
          ${s
            .replace(/^##? (.*$)/gm, '<h2 style="color: #0f172a; margin-top: 0; font-size: 24px;">$1</h2>')
            .replace(/\*\*(.*?)\*\*/g, '<strong style="color: #1d4ed8;">$1</strong>')
            .replace(/^- (.*)$/gm, '<li style="margin-bottom: 8px; color: #334155;">$1</li>')
            .replace(/\n/g, '<br/>')}
        </div>
      `).join('')}
    </div>
    <div class="slide-footer">
      <span>Notebook: <strong>${notebookName}</strong></span>
      <div style="display: flex; gap: 8px;">
        <button class="nav-btn" id="btnPrev" onclick="prevSlide()" disabled>← Previous</button>
        <button class="nav-btn" id="btnNext" onclick="nextSlide()">Next →</button>
      </div>
    </div>
  </div>

  <script>
    let cur = 0;
    const total = ${slides.length};
    function update() {
      for (let i = 0; i < total; i++) {
        const el = document.getElementById('slide-' + i);
        if (el) el.classList.toggle('active', i === cur);
      }
      document.getElementById('slideNum').textContent = 'Slide ' + (cur + 1) + ' of ' + total;
      document.getElementById('btnPrev').disabled = cur === 0;
      document.getElementById('btnNext').disabled = cur === total - 1;
    }
    function prevSlide() { if (cur > 0) { cur--; update(); } }
    function nextSlide() { if (cur < total - 1) { cur++; update(); } }
    document.addEventListener('keydown', (e) => {
      if (e.key === 'ArrowRight' || e.key === ' ') nextSlide();
      if (e.key === 'ArrowLeft') prevSlide();
    });
  </script>
</body>
</html>`;
  }

  /**
   * Extracts structured JSON data (quiz questions or flashcards) from an artifact or its raw HTML.
   */
  public static extractAppData(artifact: any): { quiz?: any[]; flashcards?: any[]; topics?: string[] } | null {
    if (!artifact) return null;
    const rawApp = artifact.rawArtifact?.app || artifact.app;
    if (rawApp?.appData) {
      try {
        const parsed = typeof rawApp.appData === 'string' ? JSON.parse(rawApp.appData) : rawApp.appData;
        if (parsed && (parsed.quiz || parsed.flashcards)) return parsed;
      } catch {}
    }

    const appHtml = rawApp?.appHtml || artifact.content;
    if (typeof appHtml === 'string') {
      const match = appHtml.match(/data-app-data="([^"]+)"/);
      if (match) {
        try {
          const decoded = match[1]
            .replace(/&quot;/g, '"')
            .replace(/&#39;/g, "'")
            .replace(/&amp;/g, '&')
            .replace(/&lt;/g, '<')
            .replace(/&gt;/g, '>');
          return JSON.parse(decoded);
        } catch {}
      }
    }
    return null;
  }

  /**
   * Formats a structured Quiz into readable Markdown with questions, options, answer key, and rationales.
   */
  public static formatQuizMarkdown(title: string, notebookName: string, quizList: any[]): string {
    let md = `# Quiz: ${title}\n\n- **Notebook:** ${notebookName}\n- **Total Questions:** ${quizList.length}\n\n---\n\n`;
    quizList.forEach((q: any, idx: number) => {
      md += `### Question ${idx + 1}\n\n${q.question}\n\n`;
      const options = q.answerOptions || [];
      options.forEach((opt: any, optIdx: number) => {
        const letter = String.fromCharCode(65 + optIdx);
        const check = opt.isCorrect ? '[x]' : '[ ]';
        const correctTag = opt.isCorrect ? ' **(Correct Answer)**' : '';
        md += `- ${check} **${letter}.** ${opt.text}${correctTag}\n`;
        if (opt.isCorrect && opt.rationale) {
          md += `  - *Rationale:* ${opt.rationale}\n`;
        }
      });
      if (q.hint) {
        md += `\n*Hint:* ${q.hint}\n`;
      }
      md += `\n---\n\n`;
    });
    return md.trim();
  }

  /**
   * Formats structured Flashcards into a clean Markdown table with Front (Prompt) and Back (Answer).
   */
  public static formatFlashcardsMarkdown(title: string, notebookName: string, flashcardsList: any[]): string {
    let md = `# Flashcards: ${title}\n\n- **Notebook:** ${notebookName}\n- **Total Cards:** ${flashcardsList.length}\n\n---\n\n`;
    md += `| # | Prompt / Question | Answer |\n|---|---|---|\n`;
    flashcardsList.forEach((card: any, idx: number) => {
      const front = (card.f || card.front || '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
      const back = (card.b || card.back || '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ');
      md += `| ${idx + 1} | ${front} | ${back} |\n`;
    });
    return md.trim();
  }

  /**
   * Generates a 100% standalone, zero-dependency, interactive HTML5 Quiz application
   * that loads instantly in any web browser without needing NotebookLM host APIs or Angular runtime.
   */
  public static renderInteractiveQuizHtml(title: string, notebookName: string, quizList: any[], topics?: string[]): string {
    const safeTitle = (title || 'Quiz').replace(/"/g, '&quot;');
    const safeNotebook = (notebookName || 'Notebook').replace(/"/g, '&quot;');
    const cleanQuizData = JSON.stringify(quizList || []);
    const cleanTopics = JSON.stringify(topics || []);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle} - Interactive Quiz</title>
  <style>
    :root {
      --bg: #0f172a;
      --card-bg: #1e293b;
      --text: #f8fafc;
      --text-muted: #94a3b8;
      --border: #334155;
      --primary: #6366f1;
      --primary-hover: #4f46e5;
      --correct: #10b981;
      --correct-bg: rgba(16, 185, 129, 0.15);
      --incorrect: #f43f5e;
      --incorrect-bg: rgba(244, 63, 94, 0.15);
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #f8fafc;
        --card-bg: #ffffff;
        --text: #0f172a;
        --text-muted: #64748b;
        --border: #e2e8f0;
        --primary: #4f46e5;
        --primary-hover: #4338ca;
        --correct: #059669;
        --correct-bg: rgba(5, 150, 105, 0.12);
        --incorrect: #e11d48;
        --incorrect-bg: rgba(225, 29, 72, 0.12);
      }
    }
    body {
      margin: 0;
      padding: 24px 16px;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Google Sans", Helvetica, Arial, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      box-sizing: border-box;
    }
    .quiz-app {
      width: 100%;
      max-width: 680px;
      display: flex;
      flex-direction: column;
      gap: 20px;
    }
    .header-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 24px;
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 4px 10px;
      border-radius: 20px;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      background: rgba(99, 102, 241, 0.15);
      color: #818cf8;
      width: fit-content;
    }
    .title {
      font-size: 22px;
      font-weight: 700;
      margin: 0;
      line-height: 1.3;
    }
    .subtitle {
      font-size: 13px;
      color: var(--text-muted);
      margin: 0;
    }
    .progress-bar-bg {
      width: 100%;
      height: 8px;
      background: var(--border);
      border-radius: 4px;
      overflow: hidden;
    }
    .progress-bar-fill {
      height: 100%;
      background: linear-gradient(90deg, #6366f1, #10b981);
      width: 0%;
      transition: width 0.3s ease;
    }
    .question-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 28px;
      display: flex;
      flex-direction: column;
      gap: 20px;
    }
    .question-meta {
      display: flex;
      justify-content: space-between;
      align-items: center;
      font-size: 13px;
      color: var(--text-muted);
      font-weight: 600;
    }
    .question-text {
      font-size: 18px;
      font-weight: 600;
      line-height: 1.5;
      margin: 0;
    }
    .options-list {
      display: flex;
      flex-direction: column;
      gap: 10px;
    }
    .option-btn {
      display: flex;
      align-items: flex-start;
      gap: 14px;
      padding: 14px 16px;
      border-radius: 12px;
      border: 1.5px solid var(--border);
      background: transparent;
      color: var(--text);
      font-size: 15px;
      line-height: 1.4;
      text-align: left;
      cursor: pointer;
      transition: all 0.2s ease;
      user-select: none;
    }
    .option-btn:hover:not(:disabled) {
      border-color: var(--primary);
      background: rgba(99, 102, 241, 0.06);
    }
    .option-letter {
      display: flex;
      align-items: center;
      justify-content: center;
      width: 24px;
      height: 24px;
      border-radius: 50%;
      background: var(--border);
      color: var(--text);
      font-size: 12px;
      font-weight: 700;
      flex-shrink: 0;
      margin-top: 1px;
    }
    .option-btn.selected-correct {
      border-color: var(--correct);
      background: var(--correct-bg);
      color: var(--text);
    }
    .option-btn.selected-correct .option-letter {
      background: var(--correct);
      color: white;
    }
    .option-btn.selected-wrong {
      border-color: var(--incorrect);
      background: var(--incorrect-bg);
      color: var(--text);
    }
    .option-btn.selected-wrong .option-letter {
      background: var(--incorrect);
      color: white;
    }
    .option-btn.revealed-correct {
      border-color: var(--correct);
      border-style: dashed;
      background: var(--correct-bg);
    }
    .rationale-box {
      border-radius: 12px;
      padding: 14px 16px;
      background: rgba(99, 102, 241, 0.1);
      border-left: 4px solid var(--primary);
      font-size: 14px;
      line-height: 1.5;
    }
    .hint-box {
      font-size: 13px;
      color: #fbbf24;
      background: rgba(251, 191, 36, 0.1);
      border: 1px solid rgba(251, 191, 36, 0.3);
      padding: 10px 14px;
      border-radius: 8px;
    }
    .btn-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-top: 8px;
    }
    .action-btn {
      padding: 10px 20px;
      border-radius: 10px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      border: none;
      transition: all 0.2s ease;
    }
    .btn-secondary {
      background: var(--border);
      color: var(--text);
    }
    .btn-secondary:hover:not(:disabled) {
      opacity: 0.8;
    }
    .btn-primary {
      background: var(--primary);
      color: #ffffff;
    }
    .btn-primary:hover:not(:disabled) {
      background: var(--primary-hover);
    }
    .action-btn:disabled {
      opacity: 0.3;
      cursor: not-allowed;
    }
    .summary-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 32px;
      text-align: center;
      display: flex;
      flex-direction: column;
      gap: 20px;
      align-items: center;
    }
    .score-circle {
      width: 120px;
      height: 120px;
      border-radius: 50%;
      border: 6px solid var(--primary);
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      font-size: 32px;
      font-weight: 800;
      color: var(--text);
    }
    .score-label {
      font-size: 11px;
      color: var(--text-muted);
      text-transform: uppercase;
      letter-spacing: 0.05em;
    }
  </style>
</head>
<body>
  <div class="quiz-app">
    <div class="header-card">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <span class="badge">🧠 NotebookLM Studio Quiz</span>
        <span style="font-size: 13px; font-weight: 600; color: var(--text-muted);" id="headerScore">Score: 0</span>
      </div>
      <h1 class="title">${safeTitle}</h1>
      <p class="subtitle">Notebook: <strong>${safeNotebook}</strong></p>
      <div class="progress-bar-bg">
        <div class="progress-bar-fill" id="progressFill"></div>
      </div>
    </div>

    <div class="question-card" id="quizCard">
      <div class="question-meta">
        <span id="questionCounter">Question 1 of 1</span>
        <button id="hintBtn" class="action-btn btn-secondary" style="padding: 4px 10px; font-size: 12px; display: none;">💡 Show Hint</button>
      </div>
      <div id="hintContent" class="hint-box" style="display: none;"></div>
      <h2 class="question-text" id="questionText"></h2>
      <div class="options-list" id="optionsContainer"></div>
      <div id="rationaleContainer" class="rationale-box" style="display: none;"></div>
      <div class="btn-row">
        <button id="prevBtn" class="action-btn btn-secondary">← Previous</button>
        <button id="nextBtn" class="action-btn btn-primary">Next →</button>
      </div>
    </div>

    <div class="summary-card" id="summaryCard" style="display: none;">
      <span class="badge">🎉 Quiz Completed!</span>
      <div class="score-circle">
        <span id="finalPercent">100%</span>
        <span class="score-label">Score</span>
      </div>
      <h2 style="margin: 0; font-size: 20px;" id="summaryHeadline">Great Job!</h2>
      <p style="margin: 0; font-size: 14px; color: var(--text-muted);" id="summaryDetail"></p>
      <div style="display: flex; gap: 12px; margin-top: 12px;">
        <button id="retakeBtn" class="action-btn btn-primary">🔄 Retake Quiz</button>
      </div>
    </div>
  </div>

  <script>
    const questions = ${cleanQuizData};
    let currentIdx = 0;
    const userAnswers = new Array(questions.length).fill(null);

    function renderQuestion() {
      if (questions.length === 0) return;
      const q = questions[currentIdx];
      document.getElementById('questionCounter').textContent = 'Question ' + (currentIdx + 1) + ' of ' + questions.length;
      document.getElementById('progressFill').style.width = ((currentIdx + 1) / questions.length * 100) + '%';
      document.getElementById('questionText').textContent = q.question;

      const hintBtn = document.getElementById('hintBtn');
      const hintContent = document.getElementById('hintContent');
      if (q.hint) {
        hintBtn.style.display = 'block';
        hintContent.style.display = 'none';
        hintContent.textContent = '💡 Hint: ' + q.hint;
        hintBtn.onclick = () => {
          hintContent.style.display = hintContent.style.display === 'none' ? 'block' : 'none';
        };
      } else {
        hintBtn.style.display = 'none';
        hintContent.style.display = 'none';
      }

      const optionsContainer = document.getElementById('optionsContainer');
      optionsContainer.innerHTML = '';
      const answered = userAnswers[currentIdx] !== null;

      (q.answerOptions || []).forEach((opt, oIdx) => {
        const letter = String.fromCharCode(65 + oIdx);
        const btn = document.createElement('button');
        btn.className = 'option-btn';
        btn.innerHTML = '<span class="option-letter">' + letter + '</span><span>' + opt.text + '</span>';

        if (answered) {
          btn.disabled = true;
          if (userAnswers[currentIdx] === oIdx) {
            btn.classList.add(opt.isCorrect ? 'selected-correct' : 'selected-wrong');
          } else if (opt.isCorrect) {
            btn.classList.add('revealed-correct');
          }
        } else {
          btn.onclick = () => selectOption(oIdx);
        }
        optionsContainer.appendChild(btn);
      });

      const rationale = document.getElementById('rationaleContainer');
      if (answered) {
        const correctOpt = (q.answerOptions || []).find(o => o.isCorrect);
        rationale.style.display = 'block';
        rationale.innerHTML = '<strong>' + (q.answerOptions[userAnswers[currentIdx]]?.isCorrect ? '✓ Correct!' : '✗ Not quite.') + '</strong> ' + (correctOpt?.rationale || '');
      } else {
        rationale.style.display = 'none';
      }

      document.getElementById('prevBtn').disabled = currentIdx === 0;
      document.getElementById('nextBtn').textContent = currentIdx === questions.length - 1 ? 'Finish Quiz ✓' : 'Next →';

      updateHeaderScore();
    }

    function selectOption(oIdx) {
      userAnswers[currentIdx] = oIdx;
      renderQuestion();
    }

    function updateHeaderScore() {
      let correct = 0;
      let answeredCount = 0;
      userAnswers.forEach((ans, i) => {
        if (ans !== null) {
          answeredCount++;
          if (questions[i]?.answerOptions?.[ans]?.isCorrect) correct++;
        }
      });
      document.getElementById('headerScore').textContent = 'Score: ' + correct + '/' + questions.length;
    }

    function showSummary() {
      document.getElementById('quizCard').style.display = 'none';
      document.getElementById('summaryCard').style.display = 'flex';

      let correct = 0;
      userAnswers.forEach((ans, i) => {
        if (questions[i]?.answerOptions?.[ans]?.isCorrect) correct++;
      });
      const pct = Math.round((correct / questions.length) * 100);
      document.getElementById('finalPercent').textContent = pct + '%';
      document.getElementById('summaryDetail').textContent = 'You got ' + correct + ' out of ' + questions.length + ' questions correct.';
    }

    document.getElementById('prevBtn').onclick = () => {
      if (currentIdx > 0) {
        currentIdx--;
        renderQuestion();
      }
    };

    document.getElementById('nextBtn').onclick = () => {
      if (currentIdx < questions.length - 1) {
        currentIdx++;
        renderQuestion();
      } else {
        showSummary();
      }
    };

    document.getElementById('retakeBtn').onclick = () => {
      userAnswers.fill(null);
      currentIdx = 0;
      document.getElementById('summaryCard').style.display = 'none';
      document.getElementById('quizCard').style.display = 'flex';
      renderQuestion();
    };

    renderQuestion();
  </script>
</body>
</html>`;
  }

  /**
   * Generates a 100% standalone, zero-dependency, interactive HTML5 3D Flashcard application
   * with flip animations, keyboard shortcuts, shuffle, and study table view.
   */
  public static renderInteractiveFlashcardsHtml(title: string, notebookName: string, flashcardsList: any[], topics?: string[]): string {
    const safeTitle = (title || 'Flashcards').replace(/"/g, '&quot;');
    const safeNotebook = (notebookName || 'Notebook').replace(/"/g, '&quot;');
    const cleanCardsData = JSON.stringify(flashcardsList || []);

    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${safeTitle} - Interactive Flashcards</title>
  <style>
    :root {
      --bg: #0f172a;
      --card-bg: #1e293b;
      --text: #f8fafc;
      --text-muted: #94a3b8;
      --border: #334155;
      --primary: #6366f1;
      --primary-hover: #4f46e5;
    }
    @media (prefers-color-scheme: light) {
      :root {
        --bg: #f8fafc;
        --card-bg: #ffffff;
        --text: #0f172a;
        --text-muted: #64748b;
        --border: #e2e8f0;
        --primary: #4f46e5;
        --primary-hover: #4338ca;
      }
    }
    body {
      margin: 0;
      padding: 24px 16px;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Google Sans", Helvetica, Arial, sans-serif;
      background-color: var(--bg);
      color: var(--text);
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      box-sizing: border-box;
    }
    .fc-app {
      width: 100%;
      max-width: 640px;
      display: flex;
      flex-direction: column;
      gap: 20px;
    }
    .header-card {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 24px;
      display: flex;
      flex-direction: column;
      gap: 12px;
    }
    .badge {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 4px 10px;
      border-radius: 20px;
      font-size: 11px;
      font-weight: 700;
      letter-spacing: 0.05em;
      text-transform: uppercase;
      background: rgba(99, 102, 241, 0.15);
      color: #818cf8;
      width: fit-content;
    }
    .title {
      font-size: 22px;
      font-weight: 700;
      margin: 0;
      line-height: 1.3;
    }
    .subtitle {
      font-size: 13px;
      color: var(--text-muted);
      margin: 0;
    }
    .progress-bar-bg {
      width: 100%;
      height: 8px;
      background: var(--border);
      border-radius: 4px;
      overflow: hidden;
    }
    .progress-bar-fill {
      height: 100%;
      background: linear-gradient(90deg, #6366f1, #38bdf8);
      width: 0%;
      transition: width 0.3s ease;
    }
    .card-scene {
      width: 100%;
      height: 340px;
      perspective: 1200px;
      cursor: pointer;
    }
    .card-flipper {
      width: 100%;
      height: 100%;
      position: relative;
      transform-style: preserve-3d;
      transition: transform 0.4s cubic-bezier(0.4, 0, 0.2, 1);
      border-radius: 20px;
      box-shadow: 0 10px 25px rgba(0, 0, 0, 0.2);
    }
    .card-flipper.flipped {
      transform: rotateY(180deg);
    }
    .card-face {
      position: absolute;
      inset: 0;
      border-radius: 20px;
      backface-visibility: hidden;
      -webkit-backface-visibility: hidden;
      display: flex;
      flex-direction: column;
      justify-content: space-between;
      padding: 32px;
      box-sizing: border-box;
    }
    .card-front {
      background: var(--card-bg);
      border: 1px solid var(--border);
    }
    .card-back {
      background: var(--card-bg);
      border: 2px solid var(--primary);
      transform: rotateY(180deg);
    }
    .card-tag {
      font-size: 11px;
      font-weight: 700;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      color: var(--primary);
    }
    .card-text {
      font-size: 20px;
      font-weight: 600;
      line-height: 1.5;
      text-align: center;
      margin: auto 0;
    }
    .card-tip {
      font-size: 12px;
      color: var(--text-muted);
      text-align: center;
    }
    .controls-row {
      display: flex;
      justify-content: space-between;
      align-items: center;
      gap: 12px;
    }
    .action-btn {
      padding: 10px 18px;
      border-radius: 12px;
      font-size: 14px;
      font-weight: 600;
      cursor: pointer;
      border: none;
      transition: all 0.2s ease;
    }
    .btn-secondary {
      background: var(--card-bg);
      border: 1px solid var(--border);
      color: var(--text);
    }
    .btn-secondary:hover:not(:disabled) {
      border-color: var(--primary);
    }
    .btn-primary {
      background: var(--primary);
      color: #ffffff;
    }
    .btn-primary:hover:not(:disabled) {
      background: var(--primary-hover);
    }
    .action-btn:disabled {
      opacity: 0.3;
      cursor: not-allowed;
    }
    .table-view {
      background: var(--card-bg);
      border: 1px solid var(--border);
      border-radius: 16px;
      padding: 24px;
      display: none;
      flex-direction: column;
      gap: 16px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      font-size: 13px;
    }
    th, td {
      padding: 10px 12px;
      border-bottom: 1px solid var(--border);
      text-align: left;
    }
    th {
      color: var(--text-muted);
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="fc-app">
    <div class="header-card">
      <div style="display: flex; justify-content: space-between; align-items: center;">
        <span class="badge">🎴 NotebookLM Flashcards</span>
        <span style="font-size: 13px; font-weight: 600; color: var(--text-muted);" id="counterLabel">Card 1 of 1</span>
      </div>
      <h1 class="title">${safeTitle}</h1>
      <p class="subtitle">Notebook: <strong>${safeNotebook}</strong></p>
      <div class="progress-bar-bg">
        <div class="progress-bar-fill" id="progressFill"></div>
      </div>
    </div>

    <div class="card-scene" id="cardScene" onclick="flipCard()">
      <div class="card-flipper" id="cardFlipper">
        <div class="card-face card-front">
          <span class="card-tag">PROMPT / QUESTION</span>
          <div class="card-text" id="frontText"></div>
          <span class="card-tip">Click card or press [Space] to flip</span>
        </div>
        <div class="card-face card-back">
          <span class="card-tag">ANSWER</span>
          <div class="card-text" id="backText"></div>
          <span class="card-tip">Click card or press [Space] to flip back</span>
        </div>
      </div>
    </div>

    <div class="controls-row">
      <button class="action-btn btn-secondary" id="prevBtn">← Prev</button>
      <button class="action-btn btn-primary" onclick="flipCard()">🔄 Flip</button>
      <button class="action-btn btn-secondary" id="nextBtn">Next →</button>
      <button class="action-btn btn-secondary" onclick="shuffleCards()">🔀 Shuffle</button>
      <button class="action-btn btn-secondary" onclick="toggleTable()">📋 Table</button>
    </div>

    <div class="table-view" id="tableView">
      <h3 style="margin: 0; font-size: 16px;">Study Sheet (All Cards)</h3>
      <table>
        <thead>
          <tr>
            <th style="width: 40px;">#</th>
            <th>Prompt / Question</th>
            <th>Answer</th>
          </tr>
        </thead>
        <tbody id="tableBody"></tbody>
      </table>
    </div>
  </div>

  <script>
    let cards = ${cleanCardsData};
    let currentIdx = 0;
    let isFlipped = false;

    function renderCard() {
      if (cards.length === 0) return;
      const c = cards[currentIdx];
      document.getElementById('counterLabel').textContent = 'Card ' + (currentIdx + 1) + ' of ' + cards.length;
      document.getElementById('progressFill').style.width = ((currentIdx + 1) / cards.length * 100) + '%';
      document.getElementById('frontText').textContent = c.f || c.front || '';
      document.getElementById('backText').textContent = c.b || c.back || '';

      const flipper = document.getElementById('cardFlipper');
      isFlipped = false;
      flipper.classList.remove('flipped');

      document.getElementById('prevBtn').disabled = currentIdx === 0;
      document.getElementById('nextBtn').disabled = currentIdx === cards.length - 1;
    }

    function flipCard() {
      const flipper = document.getElementById('cardFlipper');
      isFlipped = !isFlipped;
      flipper.classList.toggle('flipped', isFlipped);
    }

    function nextCard() {
      if (currentIdx < cards.length - 1) {
        currentIdx++;
        renderCard();
      }
    }

    function prevCard() {
      if (currentIdx > 0) {
        currentIdx--;
        renderCard();
      }
    }

    function shuffleCards() {
      for (let i = cards.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [cards[i], cards[j]] = [cards[j], cards[i]];
      }
      currentIdx = 0;
      renderCard();
      populateTable();
    }

    function toggleTable() {
      const tv = document.getElementById('tableView');
      tv.style.display = tv.style.display === 'none' || tv.style.display === '' ? 'flex' : 'none';
      if (tv.style.display === 'flex') populateTable();
    }

    function populateTable() {
      const tbody = document.getElementById('tableBody');
      tbody.innerHTML = '';
      cards.forEach((c, idx) => {
        const tr = document.createElement('tr');
        tr.innerHTML = '<td>' + (idx + 1) + '</td><td>' + (c.f || c.front || '') + '</td><td><strong>' + (c.b || c.back || '') + '</strong></td>';
        tbody.appendChild(tr);
      });
    }

    document.getElementById('prevBtn').onclick = prevCard;
    document.getElementById('nextBtn').onclick = nextCard;

    document.addEventListener('keydown', (e) => {
      if (e.key === ' ' || e.key === 'Enter') {
        e.preventDefault();
        flipCard();
      } else if (e.key === 'ArrowRight') {
        nextCard();
      } else if (e.key === 'ArrowLeft') {
        prevCard();
      }
    });

    renderCard();
  </script>
</body>
</html>`;
  }

  /**
   * Injects the missing window.notebookAppApi host bridge and removes CSP blocks
   * so raw Google NotebookLM Angular bundles don't crash when opened locally.
   */
  public static injectNotebookAppApiPolyfill(rawHtml: string): string {
    if (!rawHtml) return '';
    let html = rawHtml.replace(/<meta\s+http-equiv=["']Content-Security-Policy["'][^>]*>/gi, '');
    const polyfillScript = `
<script>
window.notebookAppApi = {
  clientType: 'notebooklm-web',
  addThemeChangeListener: function(cb) { try { cb('light'); } catch(e){} },
  notifyAppReady: function() {},
  dispatchLogEvent: function() {}
};
</script>
`;
    if (html.includes('</head>')) {
      return html.replace('</head>', `${polyfillScript}</head>`);
    }
    return polyfillScript + html;
  }
}

