apiVersion: v1
kind: Service
metadata:
  name: gemini-enterprise-admin-migration-tool
  namespace: gemini-migration
  labels:
    app.kubernetes.io/name: gemini-enterprise-admin-migration-tool
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: gemini-enterprise-admin-migration-tool
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gemini-migration-sa
  namespace: gemini-migration
  annotations:
    iam.gke.io/gcp-service-account: "gemini-admin-migration@fedex-prod-project.iam.gserviceaccount.com"
